#version 440

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#define MAX_PARTICLES 16384

uniform float deltaTime;

layout(std430, binding = 0) buffer velocities {
    vec3 velocity[MAX_PARTICLES];
};

layout(std430, binding = 1) buffer accelerations {
    vec3 acceleration[MAX_PARTICLES];
};

void main() {
    int particle = int(gl_GlobalInvocationID.x);

    const vec3 gravity = vec3(0, -1, 0) * 9.81;

    vec3 vel = velocity[particle];
    vec3 acc = acceleration[particle];

    acc += gravity * deltaTime;
    vel += acc * deltaTime;

    velocity[particle] = vel;
    acceleration[particle] = acc;
}