#version 440

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#define MAX_PARTICLES 5000

uniform float deltaTime;

layout(std430, binding = 0) buffer velocities {
    vec3 velocity[MAX_PARTICLES];
};

void main() {
    int particle = int(gl_GlobalInvocationID.x);

    vec3 vel = velocity[particle];

    vec3 dir = normalize(vel);
    float speed = min(25.0, length(vel));

    velocity[particle] = dir * speed;
}