#version 440

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#define MAX_PARTICLES 5000
#define GRID_SIZE 12 * 12 * 12
#define CELL_SIZE 100

struct Cell {
    int count;
    int list[CELL_SIZE];
};

uniform float deltaTime;

layout(std430, binding = 0) buffer grid {
    Cell cells[GRID_SIZE];
};

void main() {
    int index = int(gl_GlobalInvocationID.x);

    cells[index].count = 0;
}