#version 440

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

#define MAX_PARTICLES 16384

uniform float deltaTime;

layout(std430, binding = 0) buffer positions {
    vec3 position[MAX_PARTICLES];
};

layout(std430, binding = 1) buffer velocities {
    vec3 velocity[MAX_PARTICLES];
};

void main() {
    int particle = int(gl_GlobalInvocationID.x);

    vec3 pos = position[particle];
    vec3 vel = velocity[particle];

    pos += vel * deltaTime;

    position[particle] = pos;
}