#version 440

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#define MAX_PARTICLES 5000
#define GRID_SIZE 12 * 12 * 12
#define CELL_SIZE 100
#define BOX_TYPE 1
#define SPHERE_TYPE 0

struct Cell {
    int count;
    int list[CELL_SIZE];
};

uniform int particleCount;
uniform int partitionSpace;

layout(std430, binding = 0) buffer types {
    int type[MAX_PARTICLES];
};

layout(std430, binding = 1) buffer radii {
    float radius[MAX_PARTICLES];
};

layout(std430, binding = 2) buffer positions {
    vec3 position[MAX_PARTICLES];
};

layout(std430, binding = 3) buffer velocities {
    vec3 velocity[MAX_PARTICLES];
};

layout(std430, binding = 4) buffer grid {
    Cell cells[GRID_SIZE];
};

bool isCollidingBoxBox(int p1, int p2) {
    vec3 pos1 = position[p1];
    vec3 pos2 = position[p2];
    float rad1 = radius[p1];
    float rad2 = radius[p2];

    float xDistance = abs(pos1.x - pos2.x);
    float yDistance = abs(pos1.y - pos2.y);
    float zDistance = abs(pos1.z - pos2.z);

    bool xOverlap = xDistance <= rad1 + rad2;
    bool yOverlap = yDistance <= rad1 + rad2;
    bool zOverlap = zDistance <= rad1 + rad2;

    return xOverlap && yOverlap && zOverlap;
}

bool isCollidingBoxSphere(int p1, int p2) {
    vec3 boxPos = position[p1];
    vec3 spherePos = position[p2];
    float boxSize = radius[p1];
    float sphereRadius = radius[p2];

    vec3 minPos = boxPos - vec3(1.0) * boxSize;
    vec3 maxPos = boxPos + vec3(1.0) * boxSize;
    vec3 clampedPos = clamp(spherePos, minPos, maxPos);

    return distance(spherePos, clampedPos) < sphereRadius;
}

bool isCollidingSphereSphere(int p1, int p2) {
    float rad1 = radius[p1];
    float rad2 = radius[p2];
    vec3 pos1 = position[p1];
    vec3 pos2 = position[p2];

    float distance = length(pos2 - pos1);
    return distance < rad1 + rad2;
}

bool isCollidingParticle(int p1, int p2) {
    int type1 = type[p1];
    int type2 = type[p2];

    if (type1 == BOX_TYPE && type2 == BOX_TYPE) {
        return isCollidingBoxBox(p1, p2);
    }

    if (type1 == SPHERE_TYPE && type2 == SPHERE_TYPE) {
        return isCollidingSphereSphere(p1, p2);
    }

    if (type1 == BOX_TYPE) {
        return isCollidingBoxSphere(p1, p2);
    }

    return isCollidingBoxSphere(p2, p1);
}

void solveBoxBoxPenetration(int p1, int p2) {
    vec3 pos1 = position[p1];
    vec3 pos2 = position[p2];

    float xOverlap = pos2.x - pos1.x;
    float yOverlap = pos2.y - pos1.y;
    float zOverlap = pos2.z - pos1.z;

    vec3 overlap = vec3(xOverlap, yOverlap, zOverlap);
    vec3 normal  = normalize(overlap);
    float distance = length(overlap);

    pos1 += normal * (-distance / 2.0 + 0.0001);
    position[p1] = pos1;
}

void solveBoxSpherePenetration(int p1, int p2) {
    vec3 boxPos = position[p1];
    vec3 spherePos = position[p2];
    float boxSize = radius[p1];

    vec3 minPos = boxPos - vec3(1.0) * boxSize;
    vec3 maxPos = boxPos + vec3(1.0) * boxSize;
    vec3 clampedPos = clamp(spherePos, minPos, maxPos);

    float distance = length(spherePos - clampedPos);
    if (distance == 0.0) {
        spherePos += vec3(0.01, 0.01, -0.01);
        distance = length(spherePos - clampedPos);
    }

    vec3 normal = normalize(spherePos - clampedPos);

    boxPos += normal * (-distance / 2.0 + 0.0001);
    position[p1] = boxPos;
}

void solveSphereSpherePenetration(int p1, int p2) {
    float rad1 = radius[p1];
    float rad2 = radius[p2];
    vec3 pos1 = position[p1];
    vec3 pos2 = position[p2];

    vec3 normal = normalize(pos2 - pos1);
    float distance = length(pos2 - pos1);
    float moveAmount = rad1 + rad2 - distance;

    pos1 += normal * -((moveAmount / 2.0) + 0.00001);
    pos2 += normal * ((moveAmount / 2.0) + 0.00001);

    position[p1] = pos1;
    //position[p2] = pos2;
}

void solveParticlePenetration(int p1, int p2) {
    int type1 = type[p1];
    int type2 = type[p2];

    if (type1 == BOX_TYPE && type2 == BOX_TYPE) {
        solveBoxBoxPenetration(p1, p2);
        return;
    }

    if (type1 == SPHERE_TYPE && type2 == SPHERE_TYPE) {
        solveSphereSpherePenetration(p1, p2);
        return;
    }

    if (type1 == BOX_TYPE) {
        solveBoxSpherePenetration(p1, p2);
        return;
    }

    solveBoxSpherePenetration(p2, p1);
}

ivec3 getTriIndex(int particle) {
    vec3 pos = position[particle];

    vec3 temp = pos;
    temp.x += 6.0;
    temp.y += 1.0;
    temp.z += 6.0;

    ivec3 res;
    res.x = int(floor(temp.x));
    res.y = int(floor(temp.y));
    res.z = int(floor(temp.z));

    return res;
}

int getIndex(ivec3 triIndex) {
    return triIndex.z * (12 * 12) + triIndex.y * 12 + triIndex.x;
}

bool isInBounds(ivec3 triIndex) {
    bool isInXBounds = triIndex.x >= 0 && triIndex.x < 12;
    bool isInYBounds = triIndex.y >= 0 && triIndex.y < 12;
    bool isInZBounds = triIndex.z >= 0 && triIndex.z < 12;

    return isInXBounds && isInYBounds && isInZBounds;
}

void solveSimple(int particle) {
    vec3 pos = position[particle];
    vec3 vel = velocity[particle];

    for (int other = particle + 1; other < particleCount; other++) {
        vec3 otherPos = position[other];
        vec3 otherVel = velocity[other];

        if (isCollidingParticle(particle, other)) {
            vec3 normal = normalize(otherPos - pos);
            float distance = length(otherPos - pos);

            solveParticlePenetration(particle, other);

            vel = reflect(vel, normal) * 0.95;
            otherVel = reflect(otherVel, normal) * 0.95;

            velocity[other] = otherVel;
            velocity[particle] = vel;
        }
    }
}

void solvePartitioning(int particle) {
    vec3 pos = position[particle];
    vec3 vel = velocity[particle];

    ivec3 currentCell = getTriIndex(particle);
    for (int yOffset = -1; yOffset <= 1; yOffset++) {
        for (int zOffset = -1; zOffset <= 1; zOffset++) {
            for (int xOffset = -1; xOffset <= 1; xOffset++) {
                ivec3 offset = ivec3(xOffset, yOffset, zOffset);
                ivec3 neighborCell = currentCell + offset;
                if (!isInBounds(neighborCell)) {
                    continue;
                }

                int index = getIndex(neighborCell);
                for (int i = 0; i < cells[index].count; i++) {
                    int other = cells[index].list[i];
                    vec3 otherPos = position[other];
                    vec3 otherVel = velocity[other];

                    if (particle != other && isCollidingParticle(particle, other)) {
                        vec3 normal = normalize(otherPos - pos);
                        float distance = length(otherPos - pos);

                        solveParticlePenetration(particle, other);

                        vel = reflect(vel, normal) * 0.95;
                        velocity[particle] = vel;
                    }
                }
            }
        }
    }
}

void main() {
    int particle = int(gl_GlobalInvocationID.x);

    if (partitionSpace == 1) {
        solvePartitioning(particle);
    } else {
        solveSimple(particle);
    }
}