#version 440

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#define MAX_PARTICLES 5000
#define GRID_SIZE 12 * 12 * 12
#define CELL_SIZE 100

struct Cell {
    int count;
    int list[CELL_SIZE];
};

uniform int particleCount;
uniform int partitionSpace;

layout(std430, binding = 0) buffer radii {
    float radius[MAX_PARTICLES];
};

layout(std430, binding = 1) buffer positions {
    vec3 position[MAX_PARTICLES];
};

layout(std430, binding = 2) buffer velocities {
    vec3 velocity[MAX_PARTICLES];
};

layout(std430, binding = 3) buffer grid {
    Cell cells[GRID_SIZE];
};

bool isCollidingParticle(int p1, int p2) {
    float rad1 = radius[p1];
    float rad2 = radius[p2];
    vec3 pos1 = position[p1];
    vec3 pos2 = position[p2];

    float distance = length(pos2 - pos1);
    return distance < rad1 + rad2;
}

void solveParticlePenetration(int p1, int p2) {
    float rad1 = radius[p1];
    float rad2 = radius[p2];
    vec3 pos1 = position[p1];
    vec3 pos2 = position[p2];

    vec3 normal = normalize(pos2 - pos1);
    float distance = length(pos2 - pos1);
    float moveAmount = rad1 + rad2 - distance;

    pos1 += normal * -((moveAmount / 2.0) + 0.00001);
    pos2 += normal * ((moveAmount / 2.0) + 0.00001);

    position[p1] = pos1;
    //position[p2] = pos2;
}

ivec3 getTriIndex(int particle) {
    vec3 pos = position[particle];

    vec3 temp = pos;
    temp.x += 6.0;
    temp.y += 1.0;
    temp.z += 6.0;

    ivec3 res;
    res.x = int(floor(temp.x));
    res.y = int(floor(temp.y));
    res.z = int(floor(temp.z));

    return res;
}

int getIndex(ivec3 triIndex) {
    return triIndex.z * (12 * 12) + triIndex.y * 12 + triIndex.x;
}

bool isInBounds(ivec3 triIndex) {
    bool isInXBounds = triIndex.x >= 0 && triIndex.x < 12;
    bool isInYBounds = triIndex.y >= 0 && triIndex.y < 12;
    bool isInZBounds = triIndex.z >= 0 && triIndex.z < 12;

    return isInXBounds && isInYBounds && isInZBounds;
}

void main() {
    int particle = int(gl_GlobalInvocationID.x);

    vec3 pos = position[particle];
    vec3 vel = velocity[particle];

    if (partitionSpace == 1) {
        ivec3 currentCell = getTriIndex(particle);
        for (int yOffset = -1; yOffset <= 1; yOffset++) {
            for (int zOffset = -1; zOffset <= 1; zOffset++) {
                for (int xOffset = -1; xOffset <= 1; xOffset++) {
                    ivec3 offset = ivec3(xOffset, yOffset, zOffset);
                    ivec3 neighborCell = currentCell + offset;
                    if (!isInBounds(neighborCell)) {
                        continue;
                    }

                    int index = getIndex(neighborCell);
                    for (int i = 0; i < cells[index].count; i++) {
                        int other = cells[index].list[i];
                        vec3 otherPos = position[other];
                        vec3 otherVel = velocity[other];

                        if (particle != other && isCollidingParticle(particle, other)) {
                            vec3 normal = normalize(otherPos - pos);
                            float distance = length(otherPos - pos);

                            solveParticlePenetration(particle, other);

                            vel = reflect(vel, normal) * 0.95;
                            velocity[particle] = vel;
                        }
                    }
                }
            }
        }
    } else {
        for (int other = particle + 1; other < particleCount; other++) {
            vec3 otherPos = position[other];
            vec3 otherVel = velocity[other];

            if (isCollidingParticle(particle, other)) {
                vec3 normal = normalize(otherPos - pos);
                float distance = length(otherPos - pos);

                solveParticlePenetration(particle, other);

                vel = reflect(vel, normal) * 0.95;
                otherVel = reflect(otherVel, normal) * 0.95;

                velocity[other] = otherVel;
                velocity[particle] = vel;
            }
        }
    }
}